* Introduction
This repository contains the start of the second machine learning assignment, in
which you will train a predictor to predict sale prices for houses in Ames,
Iowa during 2006-2010. This assignment will cover a few subjects:

- Regularisation
- Hyper-parameter tuning
- Early stopping
- Interpreting learning curves.

* Repository Contents
#+begin_example
Root
 |
 +-- README.org
 |
 +-- img/
 |  |
 |  +--
 |
 +-- src/
 |  |
 |  +-- modelling.py
 |  +-- preparing_datasets.py
 |  |-- data/
 |    |
 |    +-- housing-data.txt
 |    +-- data_description.txt
#+end_example

* Assignment
The purpose of this assignment is to put some of the theories we have discussed
during the past few lectures into practice, by applying regularisation
algorithms, implementing early stopping, and interpreting learning curves of our
trained models.

The data set used for this assignment contains many more columns than the data
we have used before, and not all of these can directly be used by a model. To be
able to use all columns, we will have to develop a few functions to transform
all data into usable types. The resulting object will have to be usable using
similar methods as a scikit-learn /estimator/, and will be evaluated against a
hold-out set.
